#49/AuthView UI
honghoker/hongkimDaonProject pull request #51
Opened 2023-10-28 14:35 UTC by ungchun

## Motivation
- issue number : #49 

## Changes
- AuthView 아무 기능이 없는 UI를 그렸습니다.

## Screen Shots
|기능|스크린샷|
|:--:|:--:|
|AuthView|![Simulator Screenshot - iPhone 14 - 2023-10-28 at 23 26 05](https://github.com/honghoker/hongkimDaonProject/assets/50910456/71510ef5-dd82-46fd-955c-839274346ef5)|

## To Reviewers
- 기존에 있었던 소셜로그인, FCM 세팅, 이미지 등등 우선 다 빠져있고 단순 뷰만 그려져있습니다. 그리고 SceneDelegate 코드도 commit에 안올렸습니다.
- 모든 뷰(Dashboard, Diary...)들을 우선 다 그려놓고 파이어베이스, 알림 등 다른 기능을 붙이는게 나을지는 잘 모르겠어서, 다음주에 한번 논의해보면 좋을 거 같아요.
- BaseView도 뭔가 만들어야 할 것 같은 느낌이..
- 이번 PR에서는 앞으로 진행하면서 작성할 mark 라던가 extension등 컨벤션을 맞춰가면 좋을 거 같아요.
- 어색하거나 이상한 네이밍 추천 환영..

2023-11-02 10:18 UTC, honghoker requested changes
👍👍👍

- 기능에 대해서는 현재 코드와 같이 함수에만 연결된 상태로 두고, 필요한 기능은 나중에 기능을 붙이도록 해요.
- BaseView는 만들도록 해야겠네요.
- Mark 순서는 아래처럼 정하면 어떨까요?
  - Properties
  - Life Cycle
  - Views
  - UI
  - Actions - extension으로 분리

2023-11-02 10:18 UTC, honghoker commented on Projects/FeatureAuth/Scene/View/LoginButtonsView.swift
> +		[leftDivider, snsLoginLabel, rightDivider].forEach {
이 코드에선 문제되지 않지만, forEach로 추가되는 view가 많아질 때 그만큼 해당 줄의 길이가 늘어나 읽기 어려울 수 있어보입니다.

아래 코드처럼 변경하는건 어떨지 제안해봅니다 😀
```swift
[
   view1,
   view2
].forEach {
   view3.addSubView($0)
}
```

2023-11-02 10:18 UTC, honghoker commented on Projects/FeatureAuth/Scene/View/LoginButtonsView.swift
> +		view.backgroundColor = .black
.black이나 .label color는 DesignSystemAsset.Colors.black.color로 변경해서 사용해주세요!

2023-11-10 03:11 UTC, ungchun commented on Projects/FeatureAuth/Scene/View/LoginButtonsView.swift
> +		[leftDivider, snsLoginLabel, rightDivider].forEach {
좋아요! 수정했습니다 :)

2023-11-10 03:11 UTC, ungchun commented on Projects/FeatureAuth/Scene/View/LoginButtonsView.swift
> +		view.backgroundColor = .black
아차차..

2023-11-10 11:43 UTC, honghoker reviewed
👍👍👍

BaseView를 먼저 develop branch에 merge 시켜놓았으니 BaseView 도 같이 적용해서 올려주세요!

2023-11-18 05:32 UTC, ungchun commented
BaseView 적용했습니다 :)

2023-11-21 04:45 UTC, honghoker commented on Projects/FeatureAuth/Scene/View/LoginButtonsView.swift
> +		[googleLoginButton, appleLoginButton].forEach {
줄바꿈 누락됐습니다!

2023-11-21 04:47 UTC, honghoker approved these changes
줄바꿈 누락된 부분 코멘트 달아놨으니 해당 부분만 수정해주시고 머지해주시면 될거 같습니다!

고생하셨습니다! 👍

2023-12-21 11:56 UTC, merged